name: build
on: workflow_dispatch
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build with Maven
        run: mvn -q -DskipTests package
      - uses: actions/upload-artifact@v4
        with:
          name: MandzukuoSMPv1.0
          path: target/MandzukuoSMPv1.0.jar
