# Konfiguracja pluginu MandzukuoSMP
# Wszystkie kwoty podane w dolarach ($)

sklep:
  enabled: true
  items:
    sugar_cane:
      price: 0.50
    bamboo:
      price: 0.40
    lapis:
      price: 0.40
    book:
      price: 1.00
    arrow:
      price: 2.00
    ender_chest:
      price: 25.00
    water_bucket:
      price: 1.50

gornik:
  rewards:
    10: "5 gold_ingot"
    20: "3 diamond"
    30: "1 golden_apple"
    35: "3 lava_bucket"
    60: "$10"
    70: "10 iron_ingot"
    80: "$30"
    85: "1 enchanted_golden_apple"
    90: "$50"

economy:
  starting_balance: 0.00

settings:
  only_in_world: "mandzukuosmp"
